[build]
  command = "vite build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npx vite"
  targetPort = 5173
  port = 8899
